{"timestamp":"2025-08-03T19:18:30.664264","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-03T19:18:30.720382","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retrain_the_model.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-03T19:18:38.929818","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff41424710>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-03T19:18:42.981476","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff41897c20>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-03T19:18:51.102196","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff412ea240>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-03T19:19:07.982986","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff412eba10>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
{"timestamp":"2025-08-03T19:19:40.466859","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff4141d250>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/registered-models/alias?name=airbnb_model_prod&alias=champion","logger":"urllib3.connectionpool"}
